---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  always_update_cookbooks: true

verifier:
  name: inspec

platforms:
  - name: sbeliakou/centos-7.4-x86_64-minimal

suites:
  - name: default
    driver:
      vm_hostname: nginx-tomcat 
      network:
      - ["private_network", {ip: "192.168.10.11"}]
    run_list:
      - recipe[task1_apache_tomcat::default]
    verifier:
      inspec_tests:
        - test/smoke/default
    attributes:
